### ISSUE TITLE
issue with estimation of TC quantile positions

### ISSUE THREAD

**Issue by radinagg** [charles-plessy/CAGEr#101]
Doing some CAGEr analysis on mouse E16.5 gonadal germ cells and it seems like there is an error in the estimation of tag cluster quantile positions, which also affects the IQ width distribution (plot shown below). The issue is affecting all samples and

**Comment by charles-plessy** [comment]
Hello, I do not see the plot in this issue.  Can you also paste the output of sessionInfo() ?

**Comment by radinagg** [comment]
Hey Charles, I had started writing this earlier and posted it without realising. Turned out to be a mistake on our side, we had mixed up the sample labels so we were comparing tag clusters from one sample with CTSS positions from another sample in the browser. The issue with the IQ width distribution is due to one outlier sample, the rest are fine - this became evident when I generated the IQ width histograms separately for each sample. Sorry for the confusion!
