### ISSUE TITLE
Annotating clustered CTSS

### ISSUE THREAD

**Issue by martino-ugolini** [charles-plessy/CAGEr#103]
Hi,
I have a question: Is there a way to annotate the clustered CTSS (after clusterCTSS) after applying the clusterCTSS function, but before creating consensus CTs across samples? There is an annotation function for CTSS, for consensus CTs, but not for non-consensus CT. Is there a way around this problem?

`
ce <- clusterCTSS( ce , threshold = 1, thresholdIsTpm = TRUE , nrPassThreshold = 1, method = "distclu", maxDist = 20, removeSingletons = TRUE , keepSingletonsAbove = 5)
ce <- cumulativeCTSSdistribution(ce, clusters = "tagClusters", useMulticore = T)
ce <- quantilePositions(ce, clusters = "tagClusters", qLow = 0.1, qUp = 0.9)
TABLE <- as.data.frame(tagClustersGR(ce, sample ="ZF_unfertilized_egg", returnInterquantileWidth = TRUE,  qLow = 0.1, qUp = 0.9))
`
In this code, I would essentially like to have the "genes" and "annotation" column that is generated for the CTSS.

Have a nice day,
Martino

**Comment by charles-plessy** [comment]
Hi Martino, maybe you can have a look at `?CAGEr:::ranges2annot` and `?CAGEr:::ranges2genes`…
