### ISSUE TITLE
How to create a CAGEexp?

### ISSUE THREAD

**Issue by Always-Stude** [charles-plessy/CAGEr#109]
![1700006151831](https://github.com/charles-plessy/CAGEr/assets/146070336/be03c838-b131-42a8-87b1-b3e077d805c1)

I want to use publicdata to create a CAGEexp,but it is failed.
What should I do ? Please help me

This is my code
Samples <- FANTOM5mouseSamples[grep("primary cell",FANTOM5mouseSamples[,"type"]),]
MEF_Samples <- Samples['21',]
inputFiles=MEF_Samples$data_url
ce=CAGEexp(inputFiles=inputFiles,inputFilesType="bed"
                       ,sampleLabels=basename(inputFiles))

**Comment by Always-Stude** [comment]
@charles-plessy

**Comment by charles-plessy** [comment]
Can you try use `MEF_Samples$sample` as sample label?

**Comment by Always-Stude** [comment]
![1700040966420](https://github.com/charles-plessy/CAGEr/assets/146070336/04133005-4c73-4755-9f75-1e61c4664c36)
I see,but A new issue has arisen

**Comment by charles-plessy** [comment]
Which version are you using?

**Comment by Always-Stude** [comment]
2.0.2

**Comment by charles-plessy** [comment]
Sorry, but you need at least version 2.8 for loading URLs directly. https://bioconductor.org/packages/release/bioc/news/CAGEr/NEWS

**Comment by Always-Stude** [comment]
Thank you for your help，I have been resolve the problem after reinstalling the win10 and R-4.3.2.However, I have encountered a new problem.Why am I encountering problems while following the tutorial?Is it because there's an issue with the way the data is being loaded?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "charles-plessy/CAGEr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月15日(星期三) 下午3:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [charles-plessy/CAGEr] How to create a CAGEexp? (Issue #109)





 
Can you try use MEF_Samples$sample as sample label?

**Comment by charles-plessy** [comment]
The tutorial is being rebuilt regularly, so in principle all examples from it should work. Please open a new issue with the error message and the steps to reproduce it.
