### ISSUE TITLE
encountered an error when running plotReverseCumulatives

### ISSUE THREAD

**Issue by Always-Stude** [charles-plessy/CAGEr#110]
![1700115586774](https://github.com/charles-plessy/CAGEr/assets/146070336/a4706e46-d069-4e8c-9235-72005df0721f)
Why is this problem occurring?
I changed the parameters but encountered a new problem.
How should I solve it？
This is my code
```
Samples <- FANTOM5mouseSamples[grep("primary cell",FANTOM5mouseSamples[,"type"]),]
MEF_Samples <- Samples['21',]
inputFiles=MEF_Samples$data_url
ce=CAGEexp(inputFiles=inputFiles,inputFilesType="bed",sampleLabels=MEF_Samples$sample)
ce=getCTSS(ce)
plotReverseCumulatives(ce,fitInRange=c(1, 1000),onePlot=TRUE)
```

**Comment by Always-Stude** [comment]
@charles-plessy

**Comment by charles-plessy** [comment]
Hello,

the FANTOM5 data is in `bedScore` format.  After you correct this the plotting function works as expected.

```
ce <- CAGEexp(inputFiles=inputFiles, inputFilesType="bedScore", sampleLabels=MEF_Samples$sample)
```
