### ISSUE TITLE
normalizeTagCount "simpleTpm" fails with CAGEset

### ISSUE THREAD

**Issue by Dunjanik** [charles-plessy/CAGEr#21]
When trying to normalise CAGEset's TagCounts with `method="simpleTpm" `
 I get following error: 

> Error in (function (classes, fdef, mtable) : unable to find an inherited method for function ‘.simpleTpm’ for signature ‘"numeric"’

**Comment by charles-plessy** [comment]
Thanks for the report !  I have extended `.simpleTpm` to the whole `numeric` class and it should solve the problem.  The correction for the `3.7` branch is on its way to Bioconductor; I hope it will be available within a day or two. (PS: I erroneously close the wrong issue number in the commit message, please do not be mislead by that).
