### ISSUE TITLE
BED files supported?

### ISSUE THREAD

**Issue by pachiras** [charles-plessy/CAGEr#22]
Hi,

I recently updated my CAGEr package from ver 1.16.0 to 1.22.2.
Since then, my code keeps giving me errors at clustering:

```R
Normalizing tag count...

Filtering CTSSs below threshold...
Clustering...
        -> Normalized_S2.forCAGEr
Error in .SummarizedExperiment.charbound(j, colnames(x), fmt) :
  <RangedSummarizedExperiment>[,j] index out of bounds: chr pos strand
```

And I found the error was caused in the `.paraclu` function in `ClusteringFunctions.R`:

```R
        ctss.cluster.list <- list()
        for(s in sample.labels) {

                message("\t-> ", s)
                d <- data[,c("chr", "pos", "strand", s)]     # <- This line causes the error!
                colnames(d) <- c("chr", "pos", "strand", "tpm")
                d <- subset(d, tpm>0)
```

My code is very simple:

```R
myCAGEset <- new("CAGEset", genomeName = BSgenome,inputFiles = pathsToInputFiles, inputFilesType = "bed",sampleLabels = samplelab)

normalizeTagCount(myCAGEset, method = "simpleTpm")

clusterCTSS(object = myCAGEset, threshold = 0.2, thresholdIsTpm = TRUE, nrPassThreshold = 0.2, method = "paraclu", removeSingletons = TRUE, keepSingletonsAbove = 2, useMulticore = TRUE, nrCores = 8)
```

I also tried CAGEexp class, but it didn't work. Am I doing wrong or the BED files are not supported? 

Thank you in advance.

**Comment by charles-plessy** [comment]
sorry for the breakage.  In version `1.22.3` (on its way to Bioconductor), the `paraclu` method should work again on `CAGEset` objects.  Support for `CAGEexp` objects will need a code refactoring to better use Bioconductor classes and I do not know when it will be completed.  As an alternative, you can also run the [C++ paraclu](http://cbrc3.cbrc.jp/~martin/paraclu/) externally and feed the resulting clusters to the `CustomConsensusClusters` function.

Please let me know if v. `1.22.3` solved your problem (in which case you can close the issue).

**Comment by pachiras** [comment]
Charles-san,

Thank you for your quick fix. I appreciate it. I'll try the new version when it becomes available.

**Comment by pachiras** [comment]
Ver 1.22.3 worked flawlessly. Thanks!
