### ISSUE TITLE
annotateCTSS should work out of the box with AnnotationHub data

### ISSUE THREAD

**Issue by charles-plessy** [charles-plessy/CAGEr#30]
```
annotateCTSS(ce, AnnotationHub::AnnotationHub()[["AH75192"]])
snapshotDate(): 2019-10-29
loading from cache
Error in ranges2genes(CTSScoordinatesGR(object), ranges) : 
  Annotation must contain “gene_name” metdata.
```
The following workaround works, but it would be neat for our users if `annotateCTSS` could directly take `AnnotationHub::AnnotationHub()[["AH75192"]]` and similar objects.

```
gr <- AnnotationHub::AnnotationHub()[["AH75192"]]
gr$gene_name <- gr$Gene
annotateCTSS(ce, gr)
```

**Comment by charles-plessy** [comment]
As a temporary workaround, I am implementing support for TxDb objects (such as `AnnotationHub::AnnotationHub()[["AH75192"]])`.

**Comment by sga91** [comment]
Is there a way to keep the annotation of the clustered CTSSs? or to re-annotate them after they are formed?

**Comment by charles-plessy** [comment]
Hi Sergio, I am not sure what you mean: this issue is about extentind the `annotateCTSS()` sothat it is  capable of using `TxDb` objects instead of only `GRanges`, and so that it is smarter about finding in which metadata column the gene names are stored.

**Comment by sga91** [comment]
> Hi Sergio, I am not sure what you mean: this issue is about extentind the `annotateCTSS()` sothat it is capable of using `TxDb` objects instead of only `GRanges`, and so that it is smarter about finding in which metadata column the gene names are stored.

Hi Charles,

I am sorry if this a very dumb question and if it's a bit out of topic. I guess I was wondering whether it is possible to keep some of the annotation (transcript or gene id) within the tag clusters object.
