### ISSUE TITLE
create CAGEexp from imported bam file

### ISSUE THREAD

**Issue by ewong159** [charles-plessy/CAGEr#34]
Hi, I would like to create CAGEexp from imported bam file. 

input.file <- CAGEr:::import.bam("501_shLUC_6D_1_CAGE_trimmed_hg19_Aligned.sortedByCoord.out.bam", "bam", sequencingQualityThreshold = 10, mappingQualityThreshold = 20)

> CAGEr:::import.bam("501_shLUC_6D_1_CAGE_trimmed_hg19_Aligned.sortedByCoord.out.bam", "bam", sequencingQualityThreshold = 10, mappingQualityThreshold = 20)
	-> Filtering out low quality reads...
GRanges object with 1212937 ranges and 3 metadata columns:
              seqnames        ranges strand |                     seq                    qual read.length
                 <Rle>     <IRanges>  <Rle> |          <DNAStringSet>          <PhredQuality>   <integer>
        [1]          1   20095-20137      - | AAACAGAGAG...GCGGTGAGTC EEEEEEEEEE...EEEEEEEEEE          43
        [2]          1   56238-56280      - | CTGGCTGGCC...CTAGATTCTC EEEEEEEEEE...EEEEEEEEEE          43
        [3]          1 353309-564634      - | ACAAACCACC...ACATATTTTG </A/////A/...EEEEEAEEEE          43
        [4]          1 565287-565329      + | ACCAATCAAT...GCTATAGCAA EEEEEEEEEE...EEEEEEEEEE          43
        [5]          1 565288-565330      + | CCAATCAATA...CTATAGCAAT EEEEEEEEEE...EEEEEEEEEE          43

myCAGEset <- CAGEexp(genomeName = "BSgenome.Hsapiens.UCSC.hg19",inputFiles = input.file, inputFilesType = "bam", sampleLabels = c("labels"))

Error in `rownames<-`(`*tmp*`, value = "labels") : 
  invalid rownames length

How should l specify the rowname?

Thanks.
Elissa

**Comment by charles-plessy** [comment]
Dear Elissa,

The `CAGEexp` function's `inputFiles` argument expects plain file names. You do not need to load the files by yourself. This will be done by the `getCTSS` functions later.

Try something like:

    myCAGexp <- CAGEexp(genomeName = "BSgenome.Hsapiens.UCSC.hg19",
                        inputFiles = "501_shLUC_6D_1_CAGE_trimmed_hg19_Aligned.sortedByCoord.out.bam",
                        inputFilesType = "bam",
                        sampleLabels = "501_shLUC_6D_1")

By the way, the `import.bam` is a private function that is not meant to be used directly.  This is why it is not exported in _CAGEr_'s namespace and you had to use the `:::` operator.

I am closing this issue, but please let me know if you have further problems.

**Comment by ewong159** [comment]
Hi Charles, 
   I tried this:

myCAGexp <- CAGEexp(genomeName = "BSgenome.Hsapiens.UCSC.hg19",
                    inputFiles = "501_shLUC_6D_1_CAGE_trimmed_hg19_Aligned.sortedByCoord.out.bam",
                    inputFilesType = "bam",
                    sampleLabels = "shLUC_6D_1")
getCTSS(myCAGexp)

Reading in file: 501_shLUC_6D_1_CAGE_trimmed_hg19_Aligned.sortedByCoord.out.bam...
	-> Filtering out low quality reads...
	-> Removing the first base of the reads if 'G' and not aligned to the genome...
Error in .remove.added.G.CTSS(gr, genome, correctSystematicG = correctSystematicG) : 
  correctSystematicG not supported yet for CAGEexp objects


Alternatively, I did
bam_file <- list.files(".", full.names=T, pattern="*.bam")
cage_bam <- new("CAGEset", genomeName = "BSgenome.Hsapiens.UCSC.hg19", inputFiles = bam_file, inputFilesType = 'bam', sampleLabels = c('shLuc1','shLuc2'))
getCTSS(cage_bam_exp, mappingQualityThreshold=10)

Reading in file: ./501_shLUC_6D_1_CAGE_trimmed_hg19_Aligned.sortedByCoord.out.bam...
	-> Filtering out low quality reads...
	-> Removing the first base of the reads if 'G' and not aligned to the genome...
	-> Estimating the frequency of adding a 'G' nucleotide and correcting the systematic bias...
Error in setnames(CTSS, c("chr", "pos", "strand", sample.label)) : 
  Can't assign 4 names to a 0 column data.table


any clues?

Elissa

**Comment by charles-plessy** [comment]
Hi Elissa,

Can you try `getCTSS(myCAGexp, correctSystematicG = FALSE)` ?

PS: have a look at <https://guides.github.com/features/mastering-markdown/> for nicer display of your messages. You can use the _Preview_ tab to check your markup before posting your comment.

**Comment by ewong159** [comment]
HI Charles, 
    I tried. 

> getCTSS(myCAGexp, correctSystematicG = FALSE)

Reading in file: 501_shLUC_6D_1_CAGE_trimmed_hg19_Aligned.sortedByCoord.out.bam...
	-> Filtering out low quality reads...
	-> Removing the first base of the reads if 'G' and not aligned to the genome...
Error in checkSlotAssignment(object, name, value) : 
  assignment of an object of class “IRanges” is not valid for slot ‘ranges’ in an object of class “GPos”; is(value, "IPos") is not TRUE


may be similar to this https://support.bioconductor.org/p/78331/?

the bam was mapped with STAR and indexed by samtool. From the file it does look like i don't have chr before the chromosome number. 


It seems there is more problems with analyzing directly from bam, alternatively, how can i covert the bam to count files for analysis? may be that will be easier?

Thanks a lot for your help!
Elissa
