### ISSUE TITLE
bam2CTSS() attempts to run promoters() on a CTSS() object.

### ISSUE THREAD

**Issue by ewong159** [charles-plessy/CAGEr#36]
HI Charles, 
    I tried. 

> getCTSS(myCAGexp, correctSystematicG = FALSE)

Reading in file: 501_shLUC_6D_1_CAGE_trimmed_hg19_Aligned.sortedByCoord.out.bam...
	-> Filtering out low quality reads...
	-> Removing the first base of the reads if 'G' and not aligned to the genome...
Error in checkSlotAssignment(object, name, value) : 
  assignment of an object of class “IRanges” is not valid for slot ‘ranges’ in an object of class “GPos”; is(value, "IPos") is not TRUE

may be similar to this https://support.bioconductor.org/p/78331/?

the bam was mapped with STAR and indexed by samtool. From the file it does look like i don't have chr before the chromosome number. 

It seems there is more problems with analyzing directly from bam, alternatively, how can i covert the bam to count files for analysis? may be that will be easier?

Thanks a lot for your help!
Elissa

_Originally posted by @ewong159 in https://github.com/charles-plessy/CAGEr/issues/34#issuecomment-758698509_

**Comment by charles-plessy** [comment]
Hi Elissa, can you confirm you are using the latest release of CAGEr and Bioconductor? If yes, can you share with me your BAM file privately to my maintainer email address?

**Comment by ewong159** [comment]
Hi Charles, I am using CAGEr 1.32 and bioconductor 3.12. i sent the bam to you.....thanks a lot

Elissa

**Comment by charles-plessy** [comment]
Hi Elissa,

I am preparing a corrected version of _CAGEr_; please check after the week-end if it becomes available on Bioconductor.

In addition, I found that the alignment files that you produced use different names for the chromosomes compared with the _BSgenome.Hsapiens.UCSC.hg19_ package.  You need to convert them with a command such as the following before creating the _CAGEexp_ object.

    library("BSgenome.Hsapiens.UCSC.hg19")
    seqlevelsStyle(BSgenome.Hsapiens.UCSC.hg19) <- "NCBI"

**Comment by charles-plessy** [comment]
Hi Elissa, it took a bit of time but the corrected packages are now available on Bioconductor.
