### ISSUE TITLE
CAGEset vs CAGEexp

### ISSUE THREAD

**Issue by ewong159** [charles-plessy/CAGEr#37]
Hi Charles, 
     I am performing the analysis now. What is the differences between CAGEexp and CAGEset? I know you state in the vignette that CAGEset is the older version for storing dataset. When I do the analysis, it seems that CAGEexp has no correctsystemcaticG function so I just did FALSE. But the size of the getCTSS from CAGEexp and CAGEset are very different. So should I use one over the other (CAGEexp vs CAGEset)?
     Also, annoteCTSS does not work for CAGEset?

Elissa

**Comment by charles-plessy** [comment]
Hello, sorry for the late answer; I am removing the `CAGEset` class, so please use the `CAGEexp` one.  It is faster and use native Bioconductor classes.
