### ISSUE TITLE
Implement promoter shift functions for CAGEexp objects

### ISSUE THREAD

**Issue by charles-plessy** [charles-plessy/CAGEr#4]

**Comment by snikumbh** [comment]
Hi Charles,
I am working on this issue, and am almost there except testing the correctness of the port.

With regards to the scoreShift method in ShiftingMethods.R, what are your thoughts on how to store the computed shifting scores? 

In the earlier case, they were stored as slots like below.

```
object@consensusClustersShiftingScores <- clusters.info
object@shiftingGroupX <- groupX
object@shiftingGroupY <- groupY
object
```
See https://github.com/charles-plessy/CAGEr/blob/3e0a974ab8e240d0cac1c7404f59333d5dd62cc9/R/ShiftingMethods.R#L265


Let me know.

**Comment by charles-plessy** [comment]
Hi Sarvesh, can the scores go in the `rowData` of the consensus clusters object ?  That would be my preference.

**Comment by charles-plessy** [comment]
Now in `main`
