### ISSUE TITLE
The result is 1

### ISSUE THREAD

**Issue by houruiyan** [charles-plessy/CAGEr#66]
Hello, CAGEr team,

This is my code 
`myCAGexp <- CAGEexp(genomeName = "BSgenome.Hsapiens.UCSC.hg38",
                    inputFiles = "/storage/yhhuang/users/ruiyan/iPSC/CAGE/bk_iPSC_total_CAGE.bam",
                    inputFilesType = "bam",
                    sampleLabels = "iPSC")`

`myCAGexp <- getCTSS(myCAGexp,correctSystematicG=FALSE)`

But after I run that, I found that the value of myCAGexp is 1.  I do not know the reason. Could you give me some help? Thank you!

Best regards,
Ruiyan

**Comment by charles-plessy** [comment]
Hi Ruiyan,

can you share your BAM file with me ?

Best,

-- 
Charles Plessy

**Comment by houruiyan** [comment]
Of course, I will put it to onedrive and then send you the link. In addition, if I do not give the value of `getCTSS(myCAGexp,correctSystematicG=FALSE)` to myCAGexp. Then there is no question? 
`myCAGexp <- CAGEexp(genomeName = "BSgenome.Hsapiens.UCSC.hg38",
                    inputFiles = "/storage/yhhuang/users/ruiyan/iPSC/CAGE/bk_iPSC_total_CAGE.bam",
                    inputFilesType = "bam",
                    sampleLabels = "iPSC")`

`getCTSS(myCAGexp,correctSystematicG=FALSE)`

Then I can get this result 
<img width="613" alt="image" src="https://user-images.githubusercontent.com/56068158/193454181-f6c96ca2-8f24-48d4-9fe0-d02b2669e156.png">

Is this correct? 

Best 
Ruiyan

**Comment by houruiyan** [comment]
hello Charles,

I download the bam file from here. [https://www.ebi.ac.uk/ena/browser/view/ERR5774727?show=reads](url)  Could you download it and check it for me. I also meet some wrong at annotation setp.
`library('rtracklayer')
modelref<-import.gff3('/storage/yhhuang/users/ruiyan/annotation/human_gene_file/gencode.v41.annotation.gff3')
annotateCTSS(myCAGexp, modelref)

colData(myCAGexp)[,c("librarySizes", "promoter", "exon", "intron", "unknown")]
df<-CTSScoordinatesGR(myCAGexp)
plotAnnot(myCAGexp, "counts")`

After I use this code to run, I got this result. It is really weird.

<img width="647" alt="image" src="https://user-images.githubusercontent.com/56068158/193456144-e39079de-6070-46af-86a0-afa2308d13ba.png">
<img width="614" alt="image" src="https://user-images.githubusercontent.com/56068158/193456154-814a6f1f-9b98-4b4d-8a42-3b887bf43d24.png">



Thank you in advance.

Best regards,
Ruiyan

**Comment by charles-plessy** [comment]
Thanks for the extra information.

I think that `CAGEr` is working correctly and that the prompter rate of the iPS CAGE libraries is what your plot showed.

For instance, if I run the computation with [a FANTOM6 library](https://fantom.gsc.riken.jp/6/datafiles/Core_FANTOM6/RELEASE_latest/raw_data/Set1_human_dermal_fibroblasts/CAGE/Set1_Run1/tophat_mapping/), the promoter rate is fine.

```
myCAGexp <- CAGEexp(
  genomeName = "BSgenome.Hsapiens.UCSC.hg38",
  inputFiles = c("CNhi10452_150325_SN554_0245_AC6N6UACXX_NoIndex_L002_R1_001.F6-001-RNA-001-01C07-FE82.CAC.10003.bam", "bk_iPSC_cytoplasmic_CAGE.bam"),
  inputFilesType = "bam",
  sampleLabels = c("F6_Fibroblasts", "bk_iPSC_cytoplasmic"))

myCAGexp <- getCTSS(myCAGexp, correctSystematicG=FALSE)

modelref <- rtracklayer::import('https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_41/gencode.v41.annotation.gtf.gz')
myCAGexp <- annotateCTSS(myCAGexp, modelref)

plotAnnot(myCAGexp, "counts")
```

![image](https://user-images.githubusercontent.com/1834905/193523533-870b3c3f-87cc-43cf-8f45-b08586c467af.png)

Also, I am not sure what you meant with “_the result is 1_”, but in the below output, `A CAGEexp object of 1 listed experiment` means that the _CAGEexp_ object contains one component, which is the tag count matrix.  Have a look at the `exampleCAGEexp` object for an example containing more components.

```
A CAGEexp object of 1 listed
 experiment with a user-defined name and respective class.
 Containing an ExperimentList class object of length 1:
 [1] tagCountMatrix: RangedSummarizedExperiment with 5471926 rows and 2 columns
Functionality:
 experiments() - obtain the ExperimentList instance
 colData() - the primary/phenotype DataFrame
 sampleMap() - the sample coordination DataFrame
 `$`, `[`, `[[` - extract colData columns, subset, or experiment
 *Format() - convert into a long or wide DataFrame
 assays() - convert ExperimentList to a SimpleList of matrices
 exportClass() - save data to flat files
```

I hope that I answered all your questions.  I am closing this issue but please feel free to reopen it.

Thanks again for your feedback on CAGE.

Charles
