### ISSUE TITLE
exportToTrack (to bed) produces lines invalid for UCSC browser

### ISSUE THREAD

**Issue by ferenckata** [charles-plessy/CAGEr#74]
Hi,

I was running this piece of code:

```
brtrack <- exportToTrack(
    brcage,
    what = "tagClusters",
    qLow = 0.1,
    qUp = 0.9,
    oneTrack = FALSE)

outFileName <- paste0(outputFolder, "brcage_allsamples.bed")
rtracklayer::export.bed(
    brtrack,
    outFileName
)
```

and uploaded to UCSC genome browser, but some lines seem to have error. 
This is one such line:
chr10	7788118	7788119	.	0	+	7788118	7788119	0	3	1,36,1	0,23,0

Problem was solved when I modified it to be like this:
chr10	7788118	7788119	.	0	+	7788118	7788119	0	1	1	0

At the end I exported one by one with qLow and qUp set to NULL and there is no problem anymore with UCSC. I though I'd let you know that this might be happening with some datasets.

**Comment by charles-plessy** [comment]
Thanks for your report.  Can you share with me a subset of your data and the code that reproduces the bug, so that I can investigate it in more details?
