### ISSUE TITLE
aggregateTagClusters "address 0x4c13f1c8, cause 'memory not mapped'"

### ISSUE THREAD

**Issue by ferenckata** [charles-plessy/CAGEr#75]
Hei,

I am running CAGEr on a few different sets of data, and one of them crashes like this. I suspect that one of the samples does not have enough reads and that might cause the issue. although even in that sample, there are about 8000 unique CTSSs. I am a little bit puzzled about how to continue. Let me know if you have a good solution.

Thanks!

```# this is the line where it crashes
> brcage <- CAGEr::aggregateTagClusters(
        brcage,
        tpmThreshold = 5,
        qLow = 0.1,
        qUp = 0.9,
        maxDist = 100)

 *** caught segfault ***
address 0x4c13f1c8, cause 'memory not mapped'

 *** caught segfault ***
address 0x4c2ff184, cause 'memory not mapped'

 *** caught segfault ***

 *** caught segfault ***
address 0x4c0ff1a4, cause 'memory not mapped'

 *** caught segfault ***
address 0x4c1bf1a0, cause 'memory not mapped'

 *** caught segfault ***

 *** caught segfault ***
address 0x4c27f194, cause 'memory not mapped'

 *** caught segfault ***
address 0x4c3ff1ac, cause 'memory not mapped'

 *** caught segfault ***
address 0x4c43f180, cause 'memory not mapped'
address 0x4c1ff18c, cause 'memory not mapped'
address 0x4c0bf1a0, cause 'memory not mapped'

 *** caught segfault ***
address 0x4c4ff160, cause 'memory not mapped'
Error: no more error handlers available (recursive errors?); invoking 'abort' restart
Error: bad value

 *** caught segfault ***
address 0x4c33f178, cause 'memory not mapped'

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Error: no more error handlers available (recursive errors?); invoking 'abort' restart
Segmentation fault (core dumped)
(BRCAGE) bash-4.4$ 
```

**Comment by charles-plessy** [comment]
Hi Katalin, is there a way I can access the data ?

**Comment by ferenckata** [comment]
Sure, I will send it to you in an email

**Comment by ferenckata** [comment]
Our IT took a look and this is what he found. Note, I was actually also running it through Rscript and not interactively as he thought.

>This is tricky... I first ran this with Rscript and that didn't crash.  But running it in R did... at least most of the time, I sometimes was able to run it without it crashing.  The crashes always happened in libreadline (which is used for interactive prompts), so it kind of made sense that it didn't crash with the non-interactive Rscript.
>
>But all that is a bit of a red herring - the actual issue is somewhere entirely different.  After adding some debug output to CAGEr I tracked it down to this actually happening in data.table.  Specifically, this is in the radix_r() function in data.table's forder.c.  This is a 430 line function - based on the name I guess it implements radix sort.  There is (at least) one point where an out of bound write happens.  Basically what happens is something vaguely like this:
>
>- there is an array of numbers somewhere in memory that needs to be sorted
>- behind this array there is other data that just so happens to be the address of a function (so this points to code - the idea is that this contains some value, say 12345 and the meaning then is "go to address 12345 and run what you can find there"); this is something used by libreadline, so an entirely different component, has nothing to do with sorting, data.frame, CAGEr, ...
>- radix_r() sorts the numbers, but due to a bug also writes beyond the array
>- it overwrites the number 12345 up there, that now contains for example 123456
>- libreadline runs code from the address it thinks it should, 123456 - but that value is not a legal memory address - and it therefore crashes
>
>The bug in radix_r() probably depends on the parameter you plug in, it probably is an edge case where one comparison went wrong, something like a comparison somewhere being "<=" when it actually should be "<".  That would explain why it works so often and worked in the past but you have one data set where you have issues.
>
>I haven't had a closer look at the 400 line function with the bug.  It might be the case that just a bit of inspection reveals a wrong comparison, but this is some far from trivial code (the comments at the top of forder.c list a LOT of optimizations that went into this!), so this might also be really hard to find.
>
>There is a newer version of data.table than yours, but forder.c is unchanged there.
>
>We should report this to the authors of data.table - hopefully somebody there understands that code :).
>
>Bugs of these sort often enough only seem to happen on certain machines or with certain compilers.  But without having a very close look at what exactly is happening on some other machine where it seems to work correctly, there is no guarantee that it *really* works correctly there.  For example, if you have the same libraries on your laptop and it works there, it could be that the compiler on your laptop just happened to add some other padding to certain memory structures, so while the code was *technically* writing beyond where it was allowed to, it ended up writing somewhere that caused no bad effects whatsoever.  Or it wrote to a piece of memory where some other function stored a variable, so now you happened to overwrite a value in a table in your data somewhere.  Hard to say...
>
>One thing to note:  even if you can run your code in Rscript without it crashing (see what I wrote just at the beginning), the bug still is there and something in the libraries you are calling still does something that it should not do.  So even if it does not crash, the output might be numerically wrong.  Without knowing how exactly this is used, I cannot say if this will just be on the level of a plot looking wrong (e.g., points *should* be increasing but they are mis-sorted and there is one outlier somewhere, and the graph just looks wrong) or in the level of you getting flat out wrong numbers (entirely wrong confidence intervals, ...).
>
>I'll look at it a bit more, but I think we're at a point where it's either fairly obvious or where it is *REALLY* hard to figure out.  I don't think there is a middle ground of "it just needs a bit of extra debug statements to determine where exactly it crashes".

**Comment by charles-plessy** [comment]
Short progress report: the current stable version of _CAGEr_ does not use _data.table_ anymore in its `aggregateTagClusters` function, so the crash should not occur anymore.  But using the data you sent us I found another bug where the quantile positions are outside the _tag cluster_, leading to a crash later in the computation of the _consensus clusters_.  I do not know why the bug does not trigger with our example data.  Maybe I will follow up in another issue and close this one.

**Comment by charles-plessy** [comment]
Hi @ferenckata , I found that CAGEr has a bug related to the sort order of the sequence names, which affects your analysis too. I opened issue #79 for this; please feel free to follow up there. I will close the current issue about `data.table`, since I think that this specific problem was solved. Please reopen this issue if you have the same crashes with the latest version of CAGEr.

**Comment by ferenckata** [comment]
Great to know, thank you!
